# Generated by Django 5.1.1 on 2024-09-29 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_name', models.CharField(max_length=10, verbose_name='管理用ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquor_type', models.CharField(choices=[('gi', 'Gin'), ('vo', 'Vodka'), ('te', 'Tequila'), ('ru', 'Rum'), ('wi', 'Whisky'), ('br', 'Brandy'), ('sh', 'Shochu'), ('ot', 'Other')], max_length=2, verbose_name='アルコール種類')),
                ('bottle_name', models.CharField(max_length=20, verbose_name='酒名')),
                ('purchase_date', models.DateField(auto_now=True, verbose_name='ボトル購入日')),
                ('storage_period', models.DateField(blank=True, null=True, verbose_name='預かり期日')),
                ('is_empty', models.BooleanField(default=False, verbose_name='空ボトルか？')),
                ('management', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottle', to='app.bottlemanagement', verbose_name='管理用ID')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='店名')),
                ('address', models.CharField(max_length=50, unique=True, verbose_name='住所')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.AddField(
            model_name='bottlemanagement',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottle_management', to='app.restaurant', verbose_name='飲食店'),
        ),
    ]
